/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_c8eef56a (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/vwzmauqhnrnsqqergsgs/database/tables

import { getEnv } from "../../../lib/env.ts";
// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

let _client: ReturnType<typeof createClient> | undefined;

const client = () => {
  if (!_client) {
    _client = createClient(
      getEnv("SUPABASE_URL")!,
      getEnv("SUPABASE_SERVICE_ROLE_KEY")!,
    );
  }
  return _client;
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_c8eef56a").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_c8eef56a").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
// Returns true if the key was found and deleted, false otherwise.
export const del = async (key: string): Promise<boolean> => {
  const supabase = client();
  // select() is needed to get the count
  const { error, count } = await supabase.from("kv_store_c8eef56a").delete({ count: "exact" }).eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
  return count !== null && count > 0;
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_c8eef56a").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
// Preserves the order of input keys and returns null for missing keys.
export const mget = async (keys: string[]): Promise<any[]> => {
  if (keys.length === 0) return [];
  const supabase = client();
  // PERFORMANCE: Select both key and value to allow mapping results back to original order
  const { data, error } = await supabase.from("kv_store_c8eef56a").select("key, value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }

  // Create a map for O(1) lookup of results by key
  const resultsMap = new Map(data?.map((item) => [item.key, item.value]));

  // Return results in the exact order of requested keys
  return keys.map((key) => resultsMap.get(key) ?? null);
};

// Scan Queue (Efficient Range Query)
// Fetches keys starting with "queue:v1:" and less than or equal to endKey
export const scanQueue = async (endKey: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase.from("kv_store_c8eef56a")
    .select("key, value")
    .like("key", "queue:v1:%")
    .lte("key", endKey);

  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_c8eef56a").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string, limit?: number): Promise<any[]> => {
  const supabase = client();
  let query = supabase.from("kv_store_c8eef56a").select("key, value").like("key", prefix + "%");

  if (limit) {
    query = query.limit(limit);
  }

  const { data, error } = await query;
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};
// Search for key-value pairs by prefix and value (JSONB column query)
// Uses Supabase's arrow operators for JSONB filtering (e.g., 'value->enabled')
export const getByPrefixAndValue = async (prefix: string, jsonPath: string, value: any, limit?: number): Promise<any[]> => {
  const supabase = client();
  let query = supabase.from("kv_store_c8eef56a")
    .select("key, value")
    .like("key", prefix + "%")
    .eq(jsonPath, value);

  if (limit) {
    query = query.limit(limit);
  }

  const { data, error } = await query;
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};
