/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_c8eef56a (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/vwzmauqhnrnsqqergsgs/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

let _client: ReturnType<typeof createClient> | undefined;

const client = () => {
  if (!_client) {
    _client = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );
  }
  return _client;
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: unknown): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c8eef56a").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<unknown> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c8eef56a").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
// Returns true if the key was found and deleted, false otherwise.
export const del = async (key: string): Promise<boolean> => {
  const supabase = client()
  // select() is needed to get the count
  const { error, count } = await supabase.from("kv_store_c8eef56a").delete({ count: "exact" }).eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
  return count !== null && count > 0;
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: unknown[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c8eef56a").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<unknown[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c8eef56a").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Scan Queue (Efficient Range Query)
// Fetches keys starting with "queue:v1:" and less than or equal to endKey
export const scanQueue = async (endKey: string): Promise<unknown[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c8eef56a")
    .select("key, value")
    .like("key", "queue:v1:%")
    .lte("key", endKey);

  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c8eef56a").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<unknown[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c8eef56a").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};